### ISSUE TITLE
Doesn't detect XBox One Wireless Dongle controllers

### ISSUE THREAD

**Issue by Moros1138** [gorbit99/olcPGEX_Gamepad#6]
First, the background...

I've recently found this gem

[Linux driver for the Xbox One wireless dongle](https://github.com/medusalix/xow)

Installed and running, works perfectly in RetroArch, Steam, and Firefox (for some reason Chrome hates all of my gamepads on linux but that's a separate issue)

Ok, here's the issue.

The Xbox One Wireless system creates devices located at

```
/dev/input/js0
/dev/input/js1
```
The PGEX is looking in ``/dev/input/by-id/`` missing the wireless gamepads entirely.

When I changed the PGEX to look in ``/dev/input/`` it worked immediately and retained functionality with my wired gamepads as well.

**Comment by gorbit99** [comment]
Should be fixed by #7
